#!/bin/bash
# scratch-container.sh
#
# Builds and runs a minimal OCI container from scratch using only runc.
# No Docker, no containerd, no kubelet. Just:
#   1. A statically-linked binary as the container's init process
#   2. An OCI runtime spec (config.json) generated by runc spec
#   3. runc to execute it
#
# This demonstrates the absolute minimum required to run a container on Linux.
# runc handles: clone() for namespaces, pivot_root() for filesystem isolation,
# cgroup membership, capability dropping, seccomp filter application, and exec().
#
# Prerequisites:
#   - Linux host (kernel 4.x+ for cgroup v2, or 3.10+ for cgroup v1)
#   - runc installed (apt install runc, or download from GitHub releases)
#   - Root privileges (runc requires CAP_SYS_ADMIN for namespace creation)
#   - curl or wget (for downloading static binary)
#   - Python3 (for modifying config.json; could also use jq)
#
# Usage: sudo bash scratch-container.sh
#        sudo bash scratch-container.sh --cleanup-only

set -euo pipefail

# --- Configuration -----------------------------------------------------------

BUNDLE_DIR="/tmp/scratch-container-demo"
CONTAINER_NAME="scratch-demo-$$"  # unique name using current PID

# We use a statically-linked busybox as the container process.
# Static linking means the binary has no shared library dependencies —
# the rootfs does not need /lib/libc.so or any other library.
# This is the minimal viable rootfs: a single directory containing one binary.
BUSYBOX_URL="https://busybox.net/downloads/binaries/1.35.0-x86_64-linux-musl/busybox"

# --- Functions ---------------------------------------------------------------

log() {
    echo "[scratch-container] $*"
}

cleanup() {
    log "Cleaning up..."

    # Stop and delete the container if it is still running
    if runc state "$CONTAINER_NAME" >/dev/null 2>&1; then
        log "Stopping container: $CONTAINER_NAME"
        runc kill "$CONTAINER_NAME" SIGKILL 2>/dev/null || true
        sleep 1
        runc delete "$CONTAINER_NAME" 2>/dev/null || true
    fi

    # Remove the bundle directory
    if [ -d "$BUNDLE_DIR" ]; then
        log "Removing bundle directory: $BUNDLE_DIR"
        rm -rf "$BUNDLE_DIR"
    fi

    log "Cleanup complete."
}

# Always run cleanup on exit (success or failure)
trap cleanup EXIT

# --- Handle --cleanup-only flag ----------------------------------------------

if [ "${1:-}" = "--cleanup-only" ]; then
    log "Running cleanup only."
    cleanup
    exit 0
fi

# --- Require root ------------------------------------------------------------

if [ "$(id -u)" -ne 0 ]; then
    echo "Error: this script must be run as root (runc requires CAP_SYS_ADMIN)."
    exit 1
fi

# --- Step 1: Create the OCI bundle directory structure -----------------------
# An OCI bundle is a directory containing:
#   config.json  — the OCI Runtime Spec (process, namespaces, mounts, cgroups)
#   rootfs/      — the container's root filesystem

log "Step 1: Creating OCI bundle directory at $BUNDLE_DIR"
mkdir -p "$BUNDLE_DIR/rootfs/bin"

# The rootfs is intentionally minimal:
#   rootfs/bin/sh     -> statically-linked busybox (serves as sh, echo, cat, ls, ...)
# No libc, no /lib, no /usr — nothing. Just one binary.
# This is valid: runc will pivot_root() into this directory and exec /bin/sh.
# If /bin/sh is statically linked, it needs nothing else to run.

# --- Step 2: Download or copy a statically-linked binary into rootfs ---------

log "Step 2: Providing a statically-linked binary for the container"

# Try to find a static binary already on the system first (faster than downloading)
STATIC_BINARY=""

# Check for a statically-linked busybox (common on Alpine-based nodes)
if file /bin/busybox 2>/dev/null | grep -q "statically linked"; then
    STATIC_BINARY="/bin/busybox"
    log "Found statically-linked busybox at /bin/busybox — copying it"
fi

# Fallback: check for any static sh or dash
if [ -z "$STATIC_BINARY" ]; then
    for candidate in /usr/bin/dash /bin/dash /usr/bin/busybox; do
        if file "$candidate" 2>/dev/null | grep -q "statically linked"; then
            STATIC_BINARY="$candidate"
            log "Found statically-linked binary at $candidate — copying it"
            break
        fi
    done
fi

if [ -n "$STATIC_BINARY" ]; then
    # Copy the binary into the rootfs
    cp "$STATIC_BINARY" "$BUNDLE_DIR/rootfs/bin/sh"
    chmod 755 "$BUNDLE_DIR/rootfs/bin/sh"
else
    # Download busybox static from upstream
    log "No static binary found locally. Downloading static busybox from busybox.net..."
    if command -v curl >/dev/null 2>&1; then
        curl -sSLo "$BUNDLE_DIR/rootfs/bin/sh" "$BUSYBOX_URL"
    elif command -v wget >/dev/null 2>&1; then
        wget -qO "$BUNDLE_DIR/rootfs/bin/sh" "$BUSYBOX_URL"
    else
        echo "Error: neither curl nor wget is available. Install one or provide a static binary."
        exit 1
    fi
    chmod 755 "$BUNDLE_DIR/rootfs/bin/sh"
    log "Downloaded static busybox ($(du -sh "$BUNDLE_DIR/rootfs/bin/sh" | cut -f1))."
fi

# Verify the binary is actually statically linked
if ! file "$BUNDLE_DIR/rootfs/bin/sh" | grep -q "statically linked"; then
    echo "Warning: the binary at $BUNDLE_DIR/rootfs/bin/sh may not be statically linked."
    echo "If the container fails with 'exec: no such file or directory', it is missing shared libs."
    file "$BUNDLE_DIR/rootfs/bin/sh"
fi

log "Rootfs contents:"
find "$BUNDLE_DIR/rootfs" -type f | sort

# --- Step 3: Generate the OCI Runtime Spec -----------------------------------
# runc spec generates a default config.json with sensible defaults:
#   - process.args: ["sh"]
#   - process.terminal: true
#   - linux.namespaces: pid, ipc, uts, mount, network, cgroup
#   - linux.seccomp: large allowlist of safe syscalls
#   - linux.capabilities: limited set (no CAP_SYS_ADMIN, no CAP_NET_ADMIN, etc.)
#   - mounts: proc, sysfs, devpts, shm, mqueue, /sys/fs/cgroup
#   - root.path: "rootfs"

log "Step 3: Generating OCI Runtime Spec (config.json)"
cd "$BUNDLE_DIR"
runc spec  # writes config.json to the current directory

log "Generated config.json ($(wc -l < config.json) lines)"

# --- Step 4: Modify the spec for non-interactive execution -------------------
# The default spec runs an interactive shell (terminal: true).
# We modify it to run a non-interactive command that produces visible output.
# This avoids needing to allocate a pty in this script.
#
# We also add a simple hostname to demonstrate UTS namespace isolation.

log "Step 4: Modifying config.json for non-interactive execution"

python3 - <<'PYEOF'
import json
import sys

config_path = "config.json"

with open(config_path) as f:
    spec = json.load(f)

# Change the process to run a non-interactive command sequence.
# /bin/sh will interpret the -c argument as a shell command.
spec["process"]["args"] = [
    "/bin/sh", "-c",
    # Demonstrate what is visible from inside the container:
    # hostname (from UTS namespace), process list (from PID namespace),
    # filesystem root (from mount namespace), and kernel version (shared host kernel).
    "echo '=== Hostname (UTS namespace) ===' && "
    "hostname && "
    "echo '=== Process list (PID namespace) ===' && "
    "ps 2>/dev/null || echo '(ps not available; /proc not mounted)' && "
    "echo '=== Root filesystem (mount namespace) ===' && "
    "ls -la / && "
    "echo '=== Kernel version (shared with host) ===' && "
    "uname -r && "
    "echo '=== Running as UID/GID ===' && "
    "id 2>/dev/null || echo 'uid=0(root)'"
]

# Disable terminal allocation — we are not running interactively
spec["process"]["terminal"] = False

# Set a custom hostname to demonstrate UTS namespace isolation
spec["hostname"] = "scratch-demo"

# The default spec includes a /proc mount which enables the ps command
# and allows the container to see its own PID namespace.
# We keep it as-is since it is in the default generated spec.

# Print the final process config for visibility
print(f"Process args: {spec['process']['args']}")
print(f"Namespaces: {[ns['type'] for ns in spec.get('linux', {}).get('namespaces', [])]}")
print(f"Hostname: {spec.get('hostname', '(not set)')}")

with open(config_path, "w") as f:
    json.dump(spec, f, indent=2)

print("config.json updated successfully.")
PYEOF

# --- Step 5: Run the container -----------------------------------------------
# 'runc run' is equivalent to 'runc create' + 'runc start' + 'runc delete'.
# It:
#   1. Creates the container state directory under /run/runc/<name>/
#   2. Calls clone() with the namespace flags from config.json
#   3. In the child: calls pivot_root(), sets up mounts, applies seccomp/capabilities
#   4. Execs /bin/sh -c "..."
#   5. Waits for the process to exit
#   6. Deletes the container state
#
# After 'runc run' returns, the container is gone. No daemon remains.

log ""
log "Step 5: Running the container with runc"
log "Bundle: $BUNDLE_DIR"
log "Container name: $CONTAINER_NAME"
log "============================================================"
log ""

# runc run blocks until the container process exits.
# The EXIT trap will clean up even if this fails.
runc run --bundle "$BUNDLE_DIR" "$CONTAINER_NAME"

log ""
log "============================================================"
log "Container exited."

# --- Step 6: Demonstrate runc create / start separation ----------------------
# The above used 'runc run' which is a convenience that combines create+start.
# Here we show the two-phase lifecycle explicitly.
# This is the actual sequence that containerd-shim uses:
#   shim calls 'runc create' → container is set up but not running
#   shim calls 'runc start'  → exec() happens, runc exits, process runs
#   shim monitors the process PID for exit events

log ""
log "Step 6: Demonstrating runc create + start separation"

# Reset trap to not auto-cleanup yet (we will clean up manually in this step)
trap - EXIT

CONTAINER_NAME2="scratch-demo-2-$$"

# Phase 1: create — sets up namespaces, mounts, cgroups, seccomp
# The container process is NOT running yet. runc create blocks briefly then returns.
log "  runc create (namespace + cgroup setup, NO exec yet)..."
runc create --bundle "$BUNDLE_DIR" "$CONTAINER_NAME2"

# At this point the container exists in a "created" state.
# runc spawned an init process inside the namespaces, but the init is blocked
# waiting for the 'start' signal via the exec.fifo FIFO.
log "  Container state after create:"
runc state "$CONTAINER_NAME2" | python3 -c "
import json, sys
s = json.load(sys.stdin)
print(f'    status: {s[\"status\"]}')
print(f'    pid:    {s[\"pid\"]}')
print(f'    bundle: {s[\"bundle\"]}')
"

# The init process is visible in the host process table RIGHT NOW,
# even though the user process has not exec'd yet.
log "  runc init process in host process table:"
cat /proc/$( runc state "$CONTAINER_NAME2" 2>/dev/null | python3 -c "import json,sys; print(json.load(sys.stdin)['pid'])" 2>/dev/null || echo 0 )/status 2>/dev/null | \
    grep -E "^(Name|Pid|PPid|State):" || echo "    (process exited or not found)"

# Phase 2: start — sends the start signal; runc init calls exec(), runc start exits
log "  runc start (exec() happens, runc exits, user process runs)..."
# Because our container command exits quickly, this may complete immediately.
runc start "$CONTAINER_NAME2" || true

# Wait briefly for the process to run and exit
sleep 1

# Clean up the container state
log "  runc delete (cleans up container state)..."
runc delete "$CONTAINER_NAME2" 2>/dev/null || true

# Restore the exit trap
trap cleanup EXIT

log ""
log "============================================================"
log "Demonstration complete."
log ""
log "Key observations:"
log "  1. The rootfs is a single directory with one binary."
log "     No OS packages, no package manager, no shell scripts."
log "     runc does not care what is in rootfs/ beyond what the process needs."
log ""
log "  2. runc is not a daemon. It is a CLI tool that exits after exec()."
log "     After 'runc run' returns, there is no runc process running."
log "     In a real container runtime, the shim holds state after runc exits."
log ""
log "  3. The container ran as a fresh Linux process with:"
log "     - Its own PID namespace (PID 1 inside, but a higher PID from host view)"
log "     - Its own UTS namespace (hostname was 'scratch-demo', not the host's hostname)"
log "     - Its own mount namespace (pivot_root into $BUNDLE_DIR/rootfs)"
log "     - Its own IPC namespace"
log "     - A fresh network namespace (no network interfaces except lo)"
log "     - But the same host kernel (uname -r shows the host kernel version)"
log ""
log "  4. Capabilities were dropped. The container ran as UID 0 (root) by default"
log "     in the spec, but without most privileged capabilities."
log "     In production, set process.user.uid/gid to a non-zero value."
log ""
log "  5. Seccomp was applied from the default spec, blocking ~170 syscalls."
log "     The container could not call ptrace, bpf, kexec_load, or mount."
