apiVersion: v1
kind: Pod
metadata:
  name: with-toleration
spec:
  tolerations:
  - key: "role"
    operator: "Equal"
    value: "dedicated"
    effect: "NoSchedule"
  containers:
  - name: pause
    image: registry.k8s.io/pause:3.9
